---
title: "HPC/GPU cluster Terraform scripts"
description: "Terraform scripts deploying HPC/GPU cluster on OCI ver. 6.0"
schemaVersion: 1.0.0
version: "2024061801"
informationalText: "Terraform scripts deploying HPC/GPU cluster on OCI ver. 6.0"

# Code history
# 1.0: May 30th 2023: New release
# 2.0: Jun 17th 2023: Support resource manager stack
# 3.0: Aug 21st 2023: Support SMT and NPT BIOS settings
# 4.0: Feb 1st  2024: Change CN configuration method from individual RPMs to OCA
# 5.0: May 1st  2024: Add new feature for bastion to connect to private subnet
# 6.0: Jun 18th 2024: Add new feature for deploying HPC/GPU cluster on pre-existing VCN

#source:
#  type: marketplace
#  reference: 67628143
locale: "en"

outputs:
  bastion:
    title: "Bastion Instance Public IP"
    type: copyableString
    visible: true

variableGroups:
  - title: "General options"
    variables:
      - ${compartment_ocid}
      - ${ad}
      - ${ssh_key}
      - ${private_bastion}
      - ${exist_vcn}
      - ${vcn_ocid}
      - ${public_ocid}
      - ${private_ocid}
  - title: "Compute/GPU node options"
    variables:
      - ${cn_display_name}
      - ${comp_shape}
      - ${cn_node_count}
      - ${comp_image}
      - ${comp_boot_vol_size}
      - ${comp_cloud_config}
      - ${comp_nps_x9}
      - ${comp_nps_gpu40}
      - ${comp_nps_gpu80}
      - ${comp_smt}
  - title: "Hidden"
    variables:
      - ${vcn_params}
      - ${igw_display_name}
      - ${ngw_display_name}
      - ${subnet_params}
      - ${sl_params}
      - ${rt_params}
      - ${user_name}
      - ${inst_params_bast}
      - ${rm_pend_display_name}
      - ${comp_nps}
    visible: false

variables:
  compartment_ocid:
    type: oci:identity:compartment:id
    title: "Compartment"
    description: "Compartment where OCI resources reside"
    default: ${compartment_ocid}
    required: true
  ad:
    type: oci:identity:availabilitydomain:name
    title: "Availability Domain"
    description: "Availability Domain where OCI resources reside"
    visible: complexExpression
    dependsOn:
      compartmentId: ${compartment_ocid}
    required: true
  ssh_key:
    type: oci:core:ssh:publickey
    title: "SSH public key"
    description: "SSH public key to login to Bastion"
    required: true
  private_bastion:
    type: boolean
    title: "Private bastion"
    description: "Connect bastion to private subnet"
    default: false
  exist_vcn:
    type: boolean
    title: "Use existing VCN"
    description: "Deploy HPC/GPU cluster on existing VCN"
    default: false
  vcn_ocid:
    title: "VCN OCID"
    description: "Pre-exsisting VCN OCID for HPC/GPU cluster to be deployed in"
    visible:
      and: 
        - ${exist_vcn}
    required: true 
  public_ocid:
    title: "Public subnet OCID"
    description: "Pre-exsisting public subnet OCID for HPC/GPU cluster to be deployed in"
    visible:
      and: 
        - ${exist_vcn}
    required: true 
  private_ocid:
    title: "Private subnet OCID"
    description: "Pre-exsisting Private subnet OCID for HPC/GPU cluster to be deployed in"
    visible:
      and: 
        - ${exist_vcn}
    required: true 
  comp_shape:
    type: enum
    title: "Shape"
    description: "Compute/GPU node shape"
    enum:
      - "BM.Optimized3.36"
      - "BM.GPU4.8"
      - "BM.GPU.A100-v2.8"
    default: "BM.Optimized3.36"
    required: true
  comp_image:
    title: "Image OCID"
    description: "Compute/GPU node image OCID"
    required: true
  comp_boot_vol_size:
    type: integer
    title: "Boot volume size"
    description: "Compute/GPU node boot volume size in GB"
    required: true
    minimum: 50
    default: 100
# "-" in variable name causes issue to handle its value in Terraform scripts
  comp_cloud_config:
    type: file
    title: "cloud-config"
    description: "Compute/GPU node cloud-config file"
    required: true
  comp_nps_x9:
    type: enum
    title: "NPS for BM.Optimized3.36"
    description: "Compute/GPU node NPS (NUMA nodes Per Socket) setting in BIOS for BM.Optimized3.36"
    enum:
      - "NPS1"
      - "NPS2"
    default: "NPS1"
    required: true
    visible:
      and: 
        - or:  
          - eq:
            - ${comp_shape}
            - "BM.Optimized3.36"
  comp_nps_gpu40:
    type: enum
    title: "NPS for BM.GPU4.8"
    description: "Compute/GPU node NPS (NUMA nodes Per Socket) setting in BIOS for BM.GPU4.8"
    enum:
      - "NPS0"
      - "NPS1"
      - "NPS2"
      - "NPS4"
    default: "NPS4"
    required: true
    visible:
      and: 
        - or:  
          - eq:
            - ${comp_shape}
            - "BM.GPU4.8"
  comp_nps_gpu80:
    type: enum
    title: "NPS for BM.GPU.A100-v2.8"
    description: "Compute/GPU node NPS (NUMA nodes Per Socket) setting in BIOS for BM.GPU.A100-v2.8"
    enum:
      - "NPS0"
      - "NPS1"
      - "NPS2"
      - "NPS4"
    default: "NPS4"
    required: true
    visible:
      and: 
        - or:  
          - eq:
            - ${comp_shape}
            - "BM.GPU.A100-v2.8"
  comp_smt:
    type: boolean
    title: "SMT"
    description: "Compute/GPU node SMT (Simultanious Multi Threading) enabled in BIOS"
    default: true
  cn_display_name:
    title: "Display name postfix"
    description: "Compute/GPU node display name postfix ex) If x9-ol87, Compute/GPU node hostname becomes inst-xxxxx-x9-ol87"
    required: true
  cn_node_count:
    type: integer
    title: "Node count"
    description: "Compute/GPU node count"
    minimum: 2
    default: 2
    required: true
